services:
  app:
    container_name: png-generator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "9543:9543"
    volumes:
      - ./:/deploy
    environment:
      - TZ=Asia/Taipei
      - MEASUREMENT_ID=${MEASUREMENT_ID}
      - API_SECRET=${API_SECRET}
    working_dir: /deploy
    command: 
      - /bin/sh
      - -c
      - |
        pytest -v
        python main.py