services:
  app:
    container_name: png-generator
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #    - "9527"
    ports:
       - "9543:9543"
    environment:
      - MEASUREMENT_ID=${MEASUREMENT_ID}
      - API_SECRET=${API_SECRET}
    networks:
      - service-network
    volumes:
      - ./:/deploy
    environment:
      - TZ=Asia/Taipei
    working_dir: /deploy
    command: 
      - /bin/sh
      - -c
      - |
        pytest -v
        python main.py

networks:
  service-network:
    name: service-network
    driver: bridge
#    external: true

